config/routes.rb
Railsforcharity::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do  # Important note: The devise_for :users route must be placed above :users
    resources :avatars
    resources :locations
    resources :preferences, only: :index
    collection { post :save_preferences }
  end

  resources :tasks do
    get :new
    post :create
    resources :comments
    member { post :assign_me }
    member { post :deliver }
    member { post :unassigned }
    member { post :accept }
    member { post :reject }
  end

  resources :projects do
    resources :avatars
    resources :locations
    resources :tasks
    member { get :settings }
    member { post :vote }
    member { post :join }
    member { post :unjoin }
  end

  root :to => 'static_pages#home'

  %w(contact contact_us faq blog supporters contributors how_it_works terms tour about resources).each do |route|
    match route => "static_pages##{route}"
  end
  post 'static_pages/preview', controller: :static_pages, action: :preview

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  description    :text
#  task_type      :string(255)
#  status         :integer
#  estimated_time :integer
#  project_id     :integer
#  created_by     :integer
#  assigned_to    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  category       :integer
#

class Task < ActiveRecord::Base

  # Constants (should always be declared at the top)
  STATUSES = {
    open: 1,
    ongoing: 2,
    delivered: 3,
    done: 4
  }

  CATEGORIES = {
    programming: 1,
    designing: 2,
    testing: 3,
    art: 4,
    management: 5,
    marketing: 6,
    finance: 7,
    legal: 8
  }

  TYPES = {
    feature: 1,
    bug: 2,
    chore: 3,
    enhancement: 4
  }

  # Attributes
  attr_accessible :description, :estimated_hours, :estimated_minutes, :name, :project_id, :category, :task_type, :tag_names
  attr_accessor :tag_names, :estimated_hours, :estimated_minutes

  # Relations
  belongs_to :project
  belongs_to :creator, :class_name => 'User', :foreign_key => "created_by"
  belongs_to :assignee, :class_name => 'User', :foreign_key => "assigned_to"
  has_many :taggings, :as => :taggable, :dependent => :destroy
  has_many :tags, :through => :taggings
  has_many :comments, as: :commentable

  # Validations
  validates :name, :presence => true, :length => { :in => 2..255 }
  validates :description, :presence => true, :length => { :minimum => 20 }
  validates :category, :presence => true
  #validates :estimated_hours, :presence => true
  #validates :estimated_minutes, :presence => true
  validates :project_id, :presence => true
  validates :task_type, :presence => true, :if => :programming_task?

  accepts_nested_attributes_for :tags

  # Callbacks
  after_save :assign_tags
  before_create :make_open, :set_estimated_time
  before_save :set_estimated_time, :unless => Proc.new { |task| task.status_changed? }

  # Named Scopes
  scope :open_tasks, where(status: STATUSES[:open])
  scope :ongoing, where(status: STATUSES[:ongoing])
  scope :delivered, where(status: STATUSES[:delivered])
  scope :done, where(status: STATUSES[:done])

  def set_estimated_time
    self.estimated_time = @estimated_hours.to_i * 60 + @estimated_minutes.to_i
  end

  def estimated_hours
    self.estimated_time.to_i / 60 if self.estimated_time
  end

  def estimated_minutes
    self.estimated_time.to_i % 60 if self.estimated_time
  end

  def make_open
    self.status = Task::STATUSES[:open]
  end

  private

  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(',').map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end

  def programming_task?
    self.category == CATEGORIES[:programming]
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]

  before_filter :find_task, :only => [:edit, :show, :assign_me, :deliver, :unassigned, :accept, :reject, :update, :destroy]
  before_filter :find_user, :only => [:new, :edit, :create, :update]

  def new
    if params[:project_id] == nil
      @task = Task.new
    else
      @project = Project.find(params[:project_id])
      @task = Task.new(:project_id => @project.id)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  def create
    if params[:project_id] == nil
      @task = Task.new(params[:task])
    else
      @project = Project.find(params[:project_id])
      @task = @project.tasks.build(params[:task])
    end

    @task.creator = current_user

    respond_to do |format|
      if @task.save
        @task.tags.each { |t| t.update_attributes(:tag_type => 'task') }
        @task.project.preferences.new_task_users.each do
          |user| QC.enqueue("Emailer.send_task_email", user.id, 'new_task', @task.id)
        end

        if @project.nil?
          format.html { redirect_to :back, notice: t('controllers.tasks.create.success') }
        else
          format.html { redirect_to project_path(@project), notice: t('controllers.tasks.create.success') }
          format.json { render json: project_path(@project), status: :created, location: @task }
        end
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to :back, notice: t('controllers.tasks.update.success') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def index
    @open_tasks = Task.open_tasks.includes([:creator, :project])
    @ongoing_tasks = Task.ongoing.includes([:creator, :assignee, :project])
    @delivered_tasks = Task.delivered.includes([:creator, :assignee, :project])
    @done_tasks = Task.done.includes([:creator, :assignee, :project])
  end

  def destroy
    @task.destroy
    respond_to do |format|
      if @project.nil?
        format.html { redirect_to tasks_url }
      else
        format.html { redirect_to project_url }
        format.json { head :no_content }
      end
    end
  end

  def show
    @commentable = @task
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def assign_me
    @task.assignee = current_user
    @task.status = Task::STATUSES[:ongoing]

    if @task.save!
      if @task.creator != current_user && @task.project.preferences.task_assigned_users.include?(@task.creator)
        QC.enqueue("Emailer.send_task_email", @task.creator.id, 'task_assigned', @task.id)
      end

      redirect_to :back, notice: t('controllers.tasks.assign_me.success')
    else
      redirect_to :back, notice: t('controllers.tasks.assign_me.failure')
    end
  end

  def deliver
    @task.status = Task::STATUSES[:delivered]

    if @task.save!
      if @task.creator != current_user && @task.project.preferences.task_delivered_users.include?(@task.creator)
        QC.enqueue("Emailer.send_task_email", @task.creator.id, 'task_delivered', @task.id)
      end
      redirect_to :back, notice: t('controllers.tasks.deliver.success')
    else
      redirect_to :back, notice: t('controllers.tasks.deliver.failure')
    end
  end

  def unassigned
    @task.assigned_to = nil
    @task.status = Task::STATUSES[:open]

    if @task.save!
      if @task.creator != current_user && @task.project.preferences.task_unassigned_users.include?(@task.creator)
        QC.enqueue("Emailer.send_task_email", @task.creator.id, 'task_unassigned', @task.id)
      end
      redirect_to :back, notice: t('controllers.tasks.unassign.success')
    else
      redirect_to :back, notice: t('controllers.tasks.unassign.failure')
    end
  end

  def accept
    @task.status = Task::STATUSES[:done]

    if @task.save!
      if @task.assignee != @task.creator && @task.project.preferences.task_accepted_users.include?(@task.assignee)
        QC.enqueue("Emailer.send_task_email", @task.assignee.id, 'task_accepted', @task.id)
      end
      redirect_to :back, notice: t('controllers.tasks.accept.success')
    else
      redirect_to :back, notice: t('controllers.tasks.accept.failure')
    end
  end

  def reject
    @task.status = Task::STATUSES[:ongoing]

    if @task.save!
      if @task.assignee != @task.creator && @task.project.preferences.task_rejected_users.include?(@task.assignee)
        QC.enqueue("Emailer.send_task_email", @task.assignee.id, 'task_rejected', @task.id)
      end
      redirect_to :back, notice: t('controllers.tasks.reject.success')
    else
      redirect_to :back, notice: t('controllers.tasks.reject.failure')
    end
  end

  private

  def find_user
    @user = current_user
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
- @tags_array = Tag.find_all_by_tag_type('task').map(&:name).sort

:javascript
  $(document).ready(function() {
    $(".typeahead").tokenInput("/users.json", {
      minChars: 2,
      hintText: "Type name or username...",
      theme: "facebook",
      prePopulate: $(".typeahead").data("load"),
      preventDuplicates: true,
      resultsFormatter: function(item) {
        return "<li>" + "<img src='" + "/assets/avatar.png" + "' title='" + item.name + "' height='25px' width='25px' />" + "<div style='display: inline-block; padding-left: 10px;'><div class='name'>" + item.name + "</div></div></li>";
      }
    });

    $(".select_tags").select2({
      tags: #{@tags_array},
      tokenSeparators: [',', ' '],
      placeholder: "Select existing tags or add new ones...",
      width: '50%'
    });

    $('#task_category').on('change', function (e) {
      var value = $(this).val(),
          task_type = $('.task_type'),
          programming = "#{Task::CATEGORIES[:programming]}";

      if(value === programming) task_type.show();
      else task_type.hide();
    });
  });

-if @task.project_id
  = simple_form_for [@project, @task] do |f|
    = f.error_notification

    .form-inputs
      = f.input :project_id, :collection => @user.projects, :label_method => :name, :disabled => true
      = f.input :name, :label => 'Story Title', :input_html => { :style => 'width:50%' }
      = f.input :description, :label => 'Story Description', :input_html => { :style => 'width: 100%', :rows => 10 }
      = f.input :tag_names, :input_html => { :class => 'select_tags', data: { load: @task.tags } }, :label => 'Add Tags'
      * Estimated Time
      = f.input :estimated_hours, :label => false, :collection => 0..8, :prompt => 'Hours'
      = f.input :estimated_minutes, :label => false, :collection => (0..59).step(15), :prompt => 'Minutes'
      = f.input :category, :collection => Task::CATEGORIES.to_a.map{|a| [a.first.capitalize, a.last] }, :include_blank => false
      .task_type
        = f.input :task_type, :as => :radio, :item_wrapper_class => 'inline', :collection => ['Feature', 'Bug', 'Chore'], :include_blank => false

    .form-actions
      = f.button :submit, :class => 'btn btn-primary'

- else
  = simple_form_for [@task] do |f|
    = f.error_notification

    .form-inputs
      = f.input :project_id, :collection => @user.projects, :prompt => 'Select Project', :label_method => :name
      = f.input :name, :label => 'Story Title', :input_html => { :style => 'width:50%' }
      = f.input :description, :label => 'Story Description', :input_html => { :style => 'width: 100%', :rows => 10 }
      = f.input :tag_names, :input_html => { :class => 'select_tags', data: { load: @task.tags } }, :label => 'Add Tags'
      * Estimated Time
      = f.input :estimated_hours, :label => false, :collection => 0..8, :prompt => 'Hours'
      = f.input :estimated_minutes, :label => false, :collection => (0..59).step(15), :prompt => 'Minutes'
      = f.input :category, :collection => Task::CATEGORIES.to_a.map{|a| [a.first.capitalize, a.last] }, :include_blank => false
      .task_type
        = f.input :task_type, :as => :radio, :item_wrapper_class => 'inline', :collection => ['Feature', 'Bug', 'Chore'], :include_blank => false

    .form-actions
      = f.button :submit, :class => 'btn btn-primary'

app/views/tasks/_help.html.haml
.sidebar
  %h3
    %span.slash //
    Help
  %p
    %br
    %strong Project
    %br
    = t('views.tasks.help.project')
    %br
    %br
    %strong Story Title
    %br
    = t('views.tasks.help.title')
    %br
    %br
    %strong Description
    %br
    = t('views.tasks.help.description')
    %br
    %br
    %strong Tags
    %br
    = t('views.tasks.help.tags')
    %br
    %br
    %strong Estimated Time
    %br
    = t('views.tasks.help.estimated_time')
    %br
    %br
    %strong Category
    %br
    = t('views.tasks.help.category')
    %br
    %br
    %strong Type
    %br
    = t('views.tasks.help.type')

app/views/tasks/_info.html.haml
- project = @task.project
= ProjectPresenter.new(project, self).avatar_name
- taskp = TaskPresenter.new(@task, self)

%br
%br
%h4 Project Name
%p= project.name
%h4 Requester
%p= taskp.creator_name
- if @task.status == Task::STATUSES[:ongoing]
  %h4 Task assigned to
  = taskp.assignee_name
  %h4 Estimated time:
  #{taskp.estimated_time}
- if @task.status == Task::STATUSES[:delivered]
  %h4 Task deivered by
  = taskp.assignee_name
- if @task.status == Task::STATUSES[:done]
  %h4 Task accomplished by
  = taskp.assignee_name
- if @task.status == Task::STATUSES[:open]
  %h4 Estimated time:
  #{taskp.estimated_time}

app/views/tasks/edit.html.haml
.row
  .span8
    %h2 Editing Task
    %br
    = render :partial => 'form', :locals => { :edit => true }
  .span3
    .pull-right
      = render :partial => 'info', :locals => { :edit => true }

app/views/tasks/index.html.haml
:javascript
  $(document).ready(function() {
    $('.datatable').dataTable({
      sDom: "<'row'<'span2'l><'pull-right'f>r>t<'row'<'span3'i><'pull-right'p>>",
      iDisplayLength: 100,
      bStateSave: true
      //"bProcessing": true,
      //"bServerSide": true,
      //"sAjaxSource": $('.datatable').data('source')
    });
  });

.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a(data-toggle="tab" href="#task_open") Open
    %li
      %a(data-toggle="tab" href="#task_ongoing") Doing
    %li
      %a(data-toggle="tab" href="#task_delivered") Delivered
    %li
      %a(data-toggle="tab" href="#task_done") Done
  .tab-content
    #task_open.tab-pane.active
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Task
          %th Type
          %th Estimated Time
          %th Requested By
          %th Project Name
          %th Actions
        %tbody
          - @open_tasks.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.creator)
              %td= link_to task.project.name, project_path(task.project)
              %td
                - if task.project.users.include?(current_user)
                  = simple_form_for [task], :url => assign_me_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Let me do it!', class: 'btn-small btn-table btn-assign'
                  - if task.creator == current_user
                    = simple_form_for [@project, task], :method => :delete do |f|
                      = f.button :submit, 'Delete', :data => { :confirm => 'Are you sure?' }, class: 'btn-small btn-table'

    #task_ongoing.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Title
          %th Type
          %th Estimated Time
          %th Requested By
          %th Project Name
          %th Assigned to
          %th Actions
        %tbody
          - @ongoing_tasks.each do |task, i|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.project.name, project_path(task.project)
              %td= link_to taskp.assignee_name, user_path(task.assignee)
              %td
                = simple_form_for [task], :url => task_path(task), :method => :get do |f|
                  = f.button :submit, 'Comment', class: 'btn btn-small btn-comment'
                - if task.assignee == current_user
                  = simple_form_for [task], :url => deliver_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Deliver', class: 'btn-small btn-deliver'
                  = simple_form_for [task], :url => unassigned_task_path(task), :method => :post do |f|
                    = f.button :submit, "I can't do it", class: 'btn-small btn-unassign'

    #task_delivered.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Title
          %th Type
          %th Estimated Time
          %th Requested By
          %th Project Name
          %th Delivered By
          %th Actions
        %tbody
          - @delivered_tasks.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.project.name, project_path(task.project)
              %td= link_to task.assignee.name, user_path(task.assigned_to)
              %td
                = simple_form_for [task], :url => task_path(task), :method => :get do |f|
                  = f.button :submit, 'Comment', class: 'btn btn-small btn-comment'
                - if task.creator == current_user
                  = simple_form_for [task], :url => accept_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Accept', class: 'btn-small btn-lima'
                  = simple_form_for [task], :url => reject_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Reject', class: 'btn-small btn-warning'
    #task_done.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Title
          %th Type
          %th Requested By
          %th Project Name
          %th Accomplished By
          %th Hours Worked
        %tbody
          - @done_tasks.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.project.name, project_path(task.project)
              %td= link_to task.assignee.name, user_path(task.assigned_to)
              %td= taskp.estimated_time

app/views/tasks/new.html.haml
.row
  .span8
    %h2.heading
      %span.slash //
      New Task
    %br
    = render :partial => 'form'
  .span4
    = render :partial => 'tasks/help'

app/views/tasks/show.html.haml
- taskp = TaskPresenter.new(@task, self)
.row
  .span8
    %h4 Task Title
    = @task.name
    %br
    %br
    %h4 Task Description
    = raw syntax_highlighter(markdown.render(@task.description))
    %br
    %br
    = render :partial => 'comments/form'
    = nested_comments (@comments).arrange(:order => :created_at)

  .span3
    .pull-right
      = render :partial => 'info', :locals => { :show => true }
      %br
      %br
      - if @task.status == Task::STATUSES[:open]
        = simple_form_for [@task], :url => assign_me_task_path(@task), :method => :post do |f|
          = f.button :submit, 'Let me do it!', class: 'btn-small btn-table btn-assign'

      - if @task.status == Task::STATUSES[:ongoing] && (@task.assignee == current_user)
        = simple_form_for [@task], :url => deliver_task_path(@task), :method => :post do |f|
          = f.button :submit, 'Deliver', class: 'btn-small btn-deliver'
        = simple_form_for [@task], :url => unassigned_task_path(@task), :method => :post do |f|
          = f.button :submit, "I can't do it", class: 'btn-small btn-unassign'

      - if @task.status == Task::STATUSES[:delivered] && (@task.creator == current_user)
        = simple_form_for [@task], :url => accept_task_path(@task), :method => :post do |f|
          = f.button :submit, 'Accept', class: 'btn-small btn-lima'
        = simple_form_for [@task], :url => reject_task_path(@task), :method => :post do |f|
          = f.button :submit, 'Reject', class: 'btn-small btn-warning'

      - if @task.status != Task::STATUSES[:done]  && (@task.creator == current_user) && @task.status != Task::STATUSES[:delivered]
        = link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary'