config/routes.rb
Railsforcharity::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do  # Important note: The devise_for :users route must be placed above :users
    resources :avatars
    resources :locations
    resources :preferences, only: :index
    collection { post :save_preferences }
  end

  resources :tasks do
    get :new
    post :create
    resources :comments
    member { post :assign_me }
    member { post :deliver }
    member { post :unassigned }
    member { post :accept }
    member { post :reject }
  end

  resources :projects do
    resources :avatars
    resources :locations
    resources :tasks
    member { get :settings }
    member { post :vote }
    member { post :join }
    member { post :unjoin }
  end

  root :to => 'static_pages#home'

  %w(contact contact_us faq blog supporters contributors how_it_works terms tour about resources).each do |route|
    match route => "static_pages##{route}"
  end
  post 'static_pages/preview', controller: :static_pages, action: :preview

end

app/views/shared/_fork_me_on_github.html.haml
%a(href="https://github.com/you")
  %img(alt="Fork me on GitHub" src="https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png" style="position: absolute; top: 0; right: 0; border: 0;")

app/views/shared/_tasks.html.haml
:javascript
  $(document).ready(function() {
    $('.datatable').dataTable({
      sDom: "<'row'<'span2'l><'pull-right'f>r>t<'row'<'span3'i><'pull-right'p>>",
      iDisplayLength: 100,
      bStateSave: true
      //"bProcessing": true,
      //"bServerSide": true,
      //"sAjaxSource": $('.datatable').data('source')
    });
  });

.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a(data-toggle="tab" href="#task_open") Open
    %li
      %a(data-toggle="tab" href="#task_ongoing") On Going
    %li
      %a(data-toggle="tab" href="#task_delivered") Delivered
    %li
      %a(data-toggle="tab" href="#task_done") Done
  .tab-content
    #task_open.tab-pane.active
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th Task No.
          %th Task
          %th Description
          %th Type
          %th Estimated Time
          %th Requested By
          %th Project Name
          %th Actions
        %tbody
          - @tasks.open_tasks.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= truncate(task.description, length: 30).html_safe
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.creator)
              %td= link_to task.project.name, project_path(task.project)
              %td
                = simple_form_for [task], :url => assign_me_task_path(task), :method => :post do |f|
                  = f.button :submit, 'Assign to me', class: 'btn-small btn-table btn-assign'
                - if task.creator == current_user
                  = simple_form_for [@project, task], :method => :delete do |f|
                    = f.button :submit, 'Delete', :confirm => 'Are you sure?', class: 'btn-small btn-table'

    #task_ongoing.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th Task No.
          %th Title
          %th Description
          %th Type
          %th Estimated Time
          %th Requested By
          %th Project Name
          %th Assigned to
          %th Actions
        %tbody
          - @tasks.ongoing.each do |task, i|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= truncate(task.description, length: 30)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.project.name, project_path(task.project)
              %td= link_to taskp.assignee_name, user_path(task.assignee)
              %td
                = simple_form_for [task], :url => task_path(task), :method => :get do |f|
                  = f.button :submit, 'Comment', class: 'btn btn-small btn-comment'
                - if task.assignee == current_user
                  = simple_form_for [task], :url => deliver_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Deliver', class: 'btn-small btn-deliver'
                  = simple_form_for [task], :url => unassigned_task_path(task), :method => :post do |f|
                    = f.button :submit, "I can't do it", class: 'btn-small btn-unassign'

    #task_delivered.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th Task No.
          %th Title
          %th Description
          %th Type
          %th Estimated Time
          %th Requested By
          %th Project Name
          %th Delivered By
          %th Actions
        %tbody
          - @tasks.delivered.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= truncate(task.description, length: 30)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.project.name, project_path(task.project)
              %td= link_to task.assignee.name, user_path(task.assigned_to)
              %td
                = simple_form_for [task], :url => task_path(task), :method => :get do |f|
                  = f.button :submit, 'Comment', class: 'btn btn-small btn-comment'
                - if task.creator == current_user
                  = simple_form_for [task], :url => accept_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Accept', class: 'btn-small btn-lima'
                  = simple_form_for [task], :url => reject_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Reject', class: 'btn-small btn-warning'
    #task_done.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th Task No.
          %th Title
          %th Description
          %th Type
          %th Requested By
          %th Project Name
          %th Accomplished By
          %th Hours Worked
        %tbody
          - @tasks.done.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= truncate(task.description, length: 30)
              %td= task.task_type
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.project.name, project_path(task.project)
              %td= link_to task.assignee.name, user_path(task.assigned_to)
              %td= taskp.estimated_time