config/routes.rb
Railsforcharity::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do  # Important note: The devise_for :users route must be placed above :users
    resources :avatars
    resources :locations
    resources :preferences, only: :index
    collection { post :save_preferences }
  end

  resources :tasks do
    get :new
    post :create
    resources :comments
    member { post :assign_me }
    member { post :deliver }
    member { post :unassigned }
    member { post :accept }
    member { post :reject }
  end

  resources :projects do
    resources :avatars
    resources :locations
    resources :tasks
    member { get :settings }
    member { post :vote }
    member { post :join }
    member { post :unjoin }
  end

  root :to => 'static_pages#home'

  %w(contact contact_us faq blog supporters contributors how_it_works terms tour about resources).each do |route|
    match route => "static_pages##{route}"
  end
  post 'static_pages/preview', controller: :static_pages, action: :preview

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  created_by  :integer
#  website     :string(255)
#  profile_url :string(255)
#  status      :string(255)
#  video       :string(255)
#

class Project < ActiveRecord::Base

  # Attributes
  attr_accessible :description, :name, :title, :collaborator_tokens, :avatar_attributes, :task_attributes, :category_names, :technology_names, :website, :profile_url, :video, :terms, :status
  attr_reader :collaborator_tokens
  attr_accessor :category_names, :technology_names

  # Relations
  has_many :tasks
  has_one :location, as: :locatable, dependent: :destroy
  has_one :avatar, as: :avatarable, dependent: :destroy
  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :preferences, as: :entity, dependent: :destroy
  has_many :user_permissions, as: :entity, dependent: :destroy
  has_many :users, through: :user_permissions
  #has_many :admins, through: :user_permissions, source: :entity, source_type: 'Project', conditions: "user_permissions.role_id = #{Role::TYPES[:project_admin]}"

  belongs_to :creator, class_name: 'User', foreign_key: "created_by"

  has_reputation :votes, source: :user, aggregated_by: :sum

  # Validations
  validates :name, :presence => true, :uniqueness => true, :length => { :in => 2..40 }
  validates :title, :presence => true, :length => { :in => 10..140 }
  validates :description, :presence => true, :length => { :in => 50..2000 }
  validates :website, :length => { :maximum => 500 }
  validates :video, :length => { :maximum => 500 }
  validates :profile_url, :presence => true, :uniqueness => true, :length => { :in => 2..25 }
  validates_acceptance_of :terms, :on => :create

  #accepts_nested_attributes_for :users, :avatar, :location
  accepts_nested_attributes_for :avatar, :location

  # Named Scopes
  scope :name_like, lambda { |n| where("name ilike ?", "%#{n}%") } # WARN: Potential DB Change Problem

  # Callbacks
  after_save lambda { make_admin(creator) }, on: :create
  after_save :assign_tags

  # Attr Writers
  def collaborator_tokens=(ids_csv)
    self.user_ids = ids_csv.split(',')
  end

  def user_permissions_obj(user)
    UserPermission.find_by_entity_type_and_entity_id_and_user_id('Project', self, user)
  end

  def user_preferences_obj(user)
    Preference.find_by_entity_type_and_entity_id_and_user_id('Project', self, user)
  end

  def get_role(user)
    user_permissions_obj(user).try(:role_id)
  end

  # make_admin(user), make_collaborator(user)
  #
  # def make_admin(user)
  #   user_permission = user_permissions_obj(user) || self.user_permissions.build(:user => user)
  #   user_permission.role_id = Role::TYPES[:project_admin]
  #   user_permission.save
  # end
  [:admin, :collaborator].each do |role_name|
    define_method("make_#{role_name}") do |user|
      user_permission = user_permissions_obj(user) || self.user_permissions.build(user: user)
      user_permission.role_id = Role::TYPES[:"project_#{role_name}"]
      user_permission.save
    end

    # def is_admin?(user)
    #   self.get_role(user) == Role::TYPES[:project_admin]
    # end
    define_method("is_#{role_name}?") do |user|
      self.get_role(user) == Role::TYPES[:"project_#{role_name}"]
    end
  end

  def categories
    self.tags.where(:tag_type => 'project')
  end

  def technologies
    self.tags.where(:tag_type => 'technology')
  end

  def hours_worked
    self.tasks.done.reduce(0.0) { |sum, t| sum + t.estimated_time } / 60
  end

  def join(user)
    self.make_collaborator(user)
    Preference.create({ user: user, entity: self, properties: Preference.all_properties })
  end

  def unjoin(user)
    self.user_permissions_obj(user).destroy
    self.user_preferences_obj(user).destroy
  end

  private

  def assign_tags
    new_tags = []

    if @category_names
      @category_names.split(',').map do |name|
        new_tags << ['project', name]
      end
    end

    if @technology_names
      @technology_names.split(',').map do |name|
        new_tags << ['technology', name]
      end
    end

    self.tags = new_tags.map do |type, tag_name|
      Tag.find_or_create_by_name(tag_name, tag_type: type)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, :only => [:show, :edit, :update, :destroy, :settings, :vote, :join, :unjoin]
  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @projects = Project.find_with_reputation(:votes, :all, order: 'votes desc', :include => [:creator, :avatar, :users])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = @project.tasks.includes([:creator])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.creator = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project), notice: t('controllers.projects.create.success') }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: t('controllers.projects.update.success') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def settings
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @project.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting!"
  end

  def join
    if @project.join(current_user)
      redirect_to :back, notice: "Thank you for joining #{@project.name}!, Happy collaborating !!!"
    else
      redirect_to :back, notice: "Failed to join the project #{@project.name}, please try again later!"
    end

  end

  def unjoin
    if @project.unjoin(current_user)
      redirect_to :back, notice: "Sorry to see you leave #{@project.name}!, Hope you come back again !!!"
    else
      redirect_to :back, notice: "Aww Snap! Failed to unjoin the project #{@project.name}, please try again later!"
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_collaborators.html.haml
%h3 Contributors
- project.users.each do |user|
  %div(style="display:inline-block; padding:10px")
    - user_presenter = UserPresenter.new(user, self)
    = link_to user_presenter.avatar(size), user_path(user), title: user.name
    %br
    %p(style='text-align:center')
      = link_to user.name.scan(/\w+/).first , user_path(user)

app/views/projects/_form.html.haml
- @category_tags_array = Tag.find_all_by_tag_type('project').map(&:name).sort
- @tech_tags_array = Tag.find_all_by_tag_type('technology').map(&:name).sort
- project_presenter = ProjectPresenter.new(@project, self)

:javascript
  $(document).ready(function() {
    $(".typeahead").tokenInput("/users.json", {
      minChars: 1,
      hintText: "Type name or username...",
      theme: "facebook",
      prePopulate: $(".typeahead").data("load"),
      preventDuplicates: true,
      resultsFormatter: function(item) {
        return "<li>" + "<img src='" + "/assets/avatar.png" + "' title='" + item.name + "' height='25px' width='25px' />" + "<div style='display: inline-block; padding-left: 10px;'><div class='name'>" + item.name + "</div></div></li>";
      }
    });

    $(".category_tags").select2({
      tags: #{@category_tags_array},
      tokenSeparators: [','],
      placeholder: "Select existing tags or add new ones...",
      width: '70%'
    });

    $(".technology_tags").select2({
      tags: #{@tech_tags_array},
      tokenSeparators: [','],
      placeholder: "Select existing tags or add new ones...",
      width: '70%'
    });
  });

= simple_form_for @project do |f|
  = f.error_notification
  .pull-right
    - if @project.avatar
      = image_tag @project.avatar.image_url(:thumb).to_s
    -else
      = image_tag 'default.png'
    = f.fields_for :avatar, @project.avatar || Avatar.new do |a|
      = a.file_field :image

  .form-inputs
    = f.input :name, :label => 'Project Name'
    %br
    %br
    = f.input :title, :label => 'Mission', :input_html => { :style => 'width:90%' }
    = f.input :description, :input_html => { class: 'markdown' }
    = f.input :category_names, :input_html => { :class => 'category_tags', value: @project.categories.map(&:name).join(",") }, :label => 'Add Tags'
    = f.input :technology_names, :input_html => { :class => 'technology_tags', value: @project.technologies.map(&:name).join(",") }, :label => 'Technologies Used'
    %br
    = '* Public Profile Url'
    .input-prepend
      %span.add-on
        http://railsforcharity.org/
      - if edit
        = f.input :profile_url, :label => false, :disabled => true
      - else
        = f.input :profile_url, :label => false
    %br
    = f.input :website
    = f.input :video, :label => 'Video Pitch'
    %br
    = f.input :collaborator_tokens, :input_html => { :class => 'typeahead', data: { load: project_presenter.collaborators } }, :label => 'Add Collaborators'
    - if !edit
      %br
      = f.input :terms, :label => false, :as => :boolean, :inline_label => "By clicking on the check box, you agree with the #{link_to_blank 'Terms and Conditions', terms_path} of RailsforCharity.".html_safe

  .form-actions
    = f.button :submit, :class => 'btn btn-primary'
    &nbsp;
    = link_to 'Back', projects_path
    -if edit
      &nbsp;
      \|
      &nbsp;
      = link_to 'Show', @project

app/views/projects/_help.html.haml
.sidebar
  %h3
    %span.slash //
    Help
  %p
    %br
    %strong Name & Picture
    %br
    = t('views.projects.help.name_and_picture')
    %br
    %br
    %strong Title
    %br
    = t('views.projects.help.title')
    %br
    %br
    %strong Description
    %br
    = t('views.projects.help.description')
    %br
    %br
    %strong Website
    %br
    = t('views.projects.help.website')
    %br
    %br
    %strong Public Profile Url
    %br
    = t('views.projects.help.profile_url')
    %br
    %br
    %strong Video Url
    %br
    = t('views.projects.help.video')
    %br
    %br
    %strong Collaborators
    %br
    = t('views.projects.help.collaborators')

app/views/projects/_settings_help.html.haml
.sidebar
  %h3
    %span.slash //
    Help
  %p
    %br
    %strong Select Collaborators
    %br
    = t('views.projects.help.name')

app/views/projects/_tasks.html.haml
:javascript
  $(document).ready(function() {
    $('.datatable').dataTable({
      sDom: "<'row'<'span2'l><'pull-right'f>r>t<'row'<'span3'i><'pull-right'p>>",
      iDisplayLength: 100,
      bStateSave: true
      //"bProcessing": true,
      //"bServerSide": true,
      //"sAjaxSource": $('.datatable').data('source')
    });
  });

.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a(data-toggle="tab" href="#task_open") Open
    %li
      %a(data-toggle="tab" href="#task_ongoing") Doing
    %li
      %a(data-toggle="tab" href="#task_delivered") Delivered
    %li
      %a(data-toggle="tab" href="#task_done") Done
  .tab-content
    #task_open.tab-pane.active
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Task
          %th Type
          %th Estimated Time
          %th Requested By
          %th Actions
        %tbody
          - @tasks.open_tasks.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.creator)
              %td
                = simple_form_for [task], :url => assign_me_task_path(task), :method => :post do |f|
                  = f.button :submit, 'Let me do it!', class: 'btn-small btn-table btn-assign'
                - if task.creator == current_user
                  = simple_form_for [@project, task], :method => :delete do |f|
                    = f.button :submit, 'Delete', :confirm => 'Are you sure?', class: 'btn-small btn-table'

    #task_ongoing.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Title
          %th Type
          %th Estimated Time
          %th Requested By
          %th Assigned to
          %th Actions
        %tbody
          - @tasks.ongoing.each do |task, i|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to taskp.assignee_name, user_path(task.assignee)
              %td
                = simple_form_for [task], :url => task_path(task), :method => :get do |f|
                  = f.button :submit, 'Comment', class: 'btn btn-small btn-comment'
                - if task.assignee == current_user
                  = simple_form_for [task], :url => deliver_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Deliver', class: 'btn-small btn-deliver'
                  = simple_form_for [task], :url => unassigned_task_path(task), :method => :post do |f|
                    = f.button :submit, "I can't do it", class: 'btn-small btn-unassign'

    #task_delivered.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Title
          %th Type
          %th Estimated Time
          %th Requested By
          %th Delivered By
          %th Actions
        %tbody
          - @tasks.delivered.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= taskp.estimated_time
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.assignee.name, user_path(task.assigned_to)
              %td
                = simple_form_for [task], :url => task_path(task), :method => :get do |f|
                  = f.button :submit, 'Comment', class: 'btn btn-small btn-comment'
                - if task.creator == current_user
                  = simple_form_for [task], :url => accept_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Accept', class: 'btn-small btn-lima'
                  = simple_form_for [task], :url => reject_task_path(task), :method => :post do |f|
                    = f.button :submit, 'Reject', class: 'btn-small btn-warning'
    #task_done.tab-pane
      %table.table.table-striped.table-hover.table-bordered.datatable
        %thead
          %th #
          %th Title
          %th Type
          %th Requested By
          %th Accomplished By
          %th Hours Worked
        %tbody
          - @tasks.done.each do |task|
            - taskp = TaskPresenter.new(task, self)
            %tr
              %td= task.id
              %td= link_to task.name, task_path(task)
              %td= task.task_type
              %td= link_to task.creator.name, user_path(task.created_by)
              %td= link_to task.assignee.name, user_path(task.assigned_to)
              %td= taskp.estimated_time

app/views/projects/_vote.html.haml
- if current_user && !current_user.voted_for?(project)
  .btn
    =link_to "", vote_project_path(project, type: "up"), method: "post", class: 'icon-thumbs-up'
  .btn.btn-danger
    =link_to "", vote_project_path(project, type: "down"), method: "post", class: 'icon-thumbs-down'
=pluralize project.reputation_value_for(:votes).to_i, "vote"

app/views/projects/edit.html.haml
.row
  .span8
    %h2 Editing project

    %br
    = render :partial => 'form', :locals => { :edit => true }

  .span4
    = render :partial => 'projects/help'

app/views/projects/index.html.haml
.row.project_index
  - @projects.each do |project|
    - project_presenter = ProjectPresenter.new(project, self)
    .project_content
      %a(href="#{project_presenter.github_url}" target="_blank")
        %img.github_fork(alt="Fork me on GitHub" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png")
      .span5
        .row
          .span3
            - if project.avatar
              = link_to image_tag(project.avatar.image_url(:thumb).to_s), project_path(project)
            -else
              = image_tag 'default.png'
            .caption
              %h3=link_to project.name, project_path(project)
              %b Idea Master: #{link_to project.creator.name, user_path(project.created_by)}
          .span2
            %ul{:style=>'list-style:none'}
              %li
                - if project_presenter.is_member?
                  = link_to "Unjoin", unjoin_project_path(project_presenter), method: 'post', class: 'btn btn-danger btn-small'
                -else
                  = link_to "Join", join_project_path(project_presenter), method: 'post', class: 'btn btn-success btn-small'
                %br
                %br
              %li
                %em
                  = render :partial => 'vote', locals: { project: project }
        .row
          .span5
            %b Mission: #{project.title}
            %br
            %br
            = render :partial => 'projects/collaborators', :locals => { project: project, size: 50}
      .span4
        -if !project.video.blank? && project.video.starts_with?("http")
          %iframe{:allowfullscreen => '', :frameborder => '0', :height => '360', :src => "#{project.video}", :width => '100%'}
        -else
          %div.video
            %p.video_text Video is coming soon!
      .span2
        %p
          =raw markdown.render(truncate(project.description, length: 350 ))
          .pull-right
            = link_to "more ...", project

app/views/projects/new.html.haml
.row
  .span8
    %h2.heading
      %span.slash //
      New Project

    %br
    = render :partial => 'form', :locals => { :edit => false }

  .span4
    = render :partial => 'projects/help'

app/views/projects/settings.html.haml
:javascript
  $(document).ready(function () {
    $(".typeahead").tokenInput("/users.json", {
      minChars: 2,
      hintText: 'Type name or username...',
      theme: 'facebook',
      prePopulate: $('.typeahead').data('load'),
      resultsFormatter: function(item) {
        return "<li>" + "<img src='" + '/assets/avatar.png' + "' title='" + item.name + "' height='25px' width='25px' />" + "<div style='display: inline-block; padding-left: 10px;'><div class='name'>" + item.name + "</div></div></li>"
      },
    });
  });

.row
  .span8
    %h3 Select Collaborators
    %br
    = simple_form_for project_path(@project), :method => :put do |f|
      = f.input :collaborator_tokens, :input_html => { :class => 'typeahead' }, :label => false, data: { load: @project.users }

      .form-actions
        = f.submit 'Save', :class => 'btn btn-primary'
  .span4
    = render :partial => 'projects/settings_help'

app/views/projects/show.html.haml
.row.project_show
  - present @project do |project|
    = link_to_image("https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png", { title: "Fork me on GitHub", class: 'home_github_fork' }, project.github_url)
    .span3
      = project.avatar_name
      %br
      %h2.project_name
        = project.name
      = project.title
      %br
      = project.website
      %br
      %br
      %span
        .hours_worked
          =@project.hours_worked
          %br
          %sub Hours Worked
      %br
      %br

      -if project.status == "confirm"
        = link_to_image("#{project.travis_url}.png", { title: 'Build Status', height: '16px'}, project.travis_url)
        %br
        %br

      = render :partial => 'vote', locals: { project: project }

      - if !project.categories.empty?
        %br
        %br
        %h3 Project Categories
        - project.categories.each do |tag|
          %span.label(style="background:##{tag.color}")= tag.name
      - if !project.technologies.empty?
        %br
        %br
        %h3 Technology Stack
        - project.technologies.each do |tag|
          %span.label(style="background:##{tag.color}")= tag.name

    .span5
      -if !project.video.blank? && project.video.starts_with?("http")
        %iframe(allowfullscreen='' frameborder='0' height='360' src="#{project.video}" width='100%')
      -else
        %div.video
          %p.video_text Video is coming soon!
      -#-if can_edit?(project)
      -#  %p=link_to 'Edit project details', edit_project_path(project)

    .span4
      .sidebar
        %h3 Pitch
        %br
        %p
          = raw markdown.render(project.description)

    -#.span12
    -#  %br
    -#  %br
    -#  %h3.tasks_text Tasks
    -#  - if project.is_member?
    -#    .new_task_button
    -#      = link_to 'New Task', new_project_task_path(project), :class => 'btn btn-large btn-success'
    -#  %br
    -#  %br
    -#  = render :partial => 'projects/tasks'
    .span12
      %br
      = render :partial => 'projects/collaborators', :locals => { project: @project, size: 80 }

    .span12
      %h3 Contacts
      %br
      %span Email Address:
      %u info@railsforcharity.org
      %br
      - if project.name == "Spokenvote"
        %span Google Group Email Address:
        %u=project.google_group_email
        %a(href="#{project.google_url}" target="_blank")
          %p Join #{project.name} Google Group