config/routes.rb
Railsforcharity::Application.routes.draw do

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :users do  # Important note: The devise_for :users route must be placed above :users
    resources :avatars
    resources :locations
    resources :preferences, only: :index
    collection { post :save_preferences }
  end

  resources :tasks do
    get :new
    post :create
    resources :comments
    member { post :assign_me }
    member { post :deliver }
    member { post :unassigned }
    member { post :accept }
    member { post :reject }
  end

  resources :projects do
    resources :avatars
    resources :locations
    resources :tasks
    member { get :settings }
    member { post :vote }
    member { post :join }
    member { post :unjoin }
  end

  root :to => 'static_pages#home'

  %w(contact contact_us faq blog supporters contributors how_it_works terms tour about resources).each do |route|
    match route => "static_pages##{route}"
  end
  post 'static_pages/preview', controller: :static_pages, action: :preview

end

app/views/layouts/_footer.html.haml
-#%a.btn.btn-navbar(data-target='.nav-collapse' data-toggle='collapse')
-#  %span.icon-bar
-#  %span.icon-bar
-#  %span.icon-bar
-#.nav-collapse
%footer
  %ul
    %li
      = link_to t('views.layouts._navigation.faq'), faq_path
    %li
      = link_to t('views.layouts._navigation.contact_us'), contact_path
    %li
      = link_to t('views.layouts._navigation.blog'), '/blog'
    %li
      = link_to t('views.layouts._navigation.about_us'), about_path
    %li
      = link_to t('views.layouts._navigation.terms'), terms_path

app/views/layouts/_ga.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34393780-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_head.html.haml
%head
  %meta(charset="utf-8")
  %meta(http-equiv="X-UA-Compatible" content="IE=edge,chrome=1")
  %meta(name="google-site-verification" content="QSkBYTANwd-a54jLK8OpuITe1yZpIsF93DlqlPnM6PY")
  %meta(name="viewport" content="width=device-width initial-scale=1 maximum-scale=1")
  %link(rel="shortcut icon" href="favicon.ico" type="image/x-icon")
  %link(rel="icon" href="favicon.ico" type="image/x-icon")
  %title= content_for?(:title) ? yield(:title) : "Rails For Charity"
  %meta(content="" name="description")
  %meta(content="" name="author")
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  = yield(:head)
  - if Rails.env.production?
    = render :partial => 'layouts/ga'

app/views/layouts/_messages.html.haml
.messages
  - flash.each do |name, msg|
    %div(class="alert alert-#{name == :notice ? "success" : "error"}")
      %a.close{"data-dismiss" => "alert"} &#215;
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
:javascript
  $(document).ready(function () {
    function goToByScroll(id){
      $('html, body').animate({scrollTop: $(id).offset().top}, 'slow');
    }

    $('.how_it_works').click(function () {
      goToByScroll("#how_it_works");
      return false;
    });

    $('.supporters').click(function () {
      goToByScroll("#supporters");
      return false;
    });
  });

%a.btn.btn-navbar(data-target='.nav-collapse' data-toggle='collapse')
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar
%a(href='/' class='brand')
  %span(style='color:red') Rails
  %span(style='color:white') for
  %span(style='color:lightgreen') Charity

.nav-collapse
  %ul.pull-left.nav
    %li
      = link_to t('views.layouts._navigation.submit_project'), new_project_path
    %li
      = link_to t('views.layouts._navigation.projects'), projects_path
    %li
      -#= link_to t('views.layouts._navigation.browse_tasks'), tasks_path
    %li
      -#= link_to t('views.layouts._navigation.new_task'), new_task_path
    -#%li
    -#  = link_to t('views.layouts._navigation.resources'), resources_path

  -if user_signed_in?
    %ul.pull-right.nav
      %li.dropdown
        = link_to raw(current_user.name + '<b class="caret"></b>'), '#', :class => 'dropdown-toggle', :data => { :toggle => 'dropdown' }
        %ul.dropdown-menu
          %li
            %a(href="#{edit_user_path(current_user)}")
              %i(class="icon-edit")
              =t('views.layouts._navigation.edit_profile')
          %li
            %a(href="#{user_preferences_path(current_user)}")
              %i(class="icon-adjust")
              =t('views.layouts._navigation.preferences')
          %li
            %a(href="#{destroy_user_session_path}" data-method='delete')
              %i(class="icon-off")
              =t('views.layouts._navigation.log_out')

  -else
    %ul.nav.pull-right
      %li.how_it_works
        = link_to 'How it works?', root_path + '#how_it_works'
      %li.supporters
        = link_to 'Supporters', root_path + '#supporters'
      = link_to t('views.layouts._navigation.log_in'), new_user_session_path, :class => 'btn btn-warning'

app/views/layouts/application.html.haml
!!!
%html
  = render :partial => 'layouts/head'
  %body
    %header
      .navbar.navbar-fixed-top
        %nav.navbar-inner
          .container
            = render 'layouts/navigation'
    .wrap
      .container
        = render 'layouts/messages'
      .container.main
        =yield
    = render 'layouts/footer'

app/views/layouts/home.html.haml
!!!
%html
  = render :partial => 'layouts/head'
  %body
    %header
      .navbar.navbar-fixed-top
        %nav.navbar-inner
          .container
            = render 'layouts/navigation'
    .container
      = render 'layouts/messages'
    = yield
    = render 'layouts/footer'

app/views/layouts/static_pages.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    <!-- Google site -->
    %meta(name="google-site-verification" content="QSkBYTANwd-a54jLK8OpuITe1yZpIsF93DlqlPnM6PY")
    <!-- /Google site -->

    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    <!-- Favicon -->
    %link{:href => "assets/icons/favicon.ico", :rel => "icon", :type => "image/ico"}
    <!-- /Favicon -->

    <!-- Title -->
    %title= content_for?(:title) ? yield(:title) : "Rails For Charity"
    <!-- /Title -->

    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    <!-- CSS & JS -->
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    <!-- /CSS & JS -->

    = csrf_meta_tags
    = yield(:head)
    <!-- Google Analytics -->
    - if Rails.env.production?
      = render :partial => 'layouts/ga'
    <!-- /Google Analytics -->

  %body
    = render 'layouts/messages'
    %br
    <!-- Content -->
    #content
      = content_for?(:content) ? yield(:content) : yield
    <!-- Content -->

    <!-- Footer -->
    .navbar.navbar-fixed-bottom
      %nav.navbar-inner
        = render 'layouts/footer'
    <!-- /Footer -->